Countries:
    type: entity
    table: countries
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        dialCode:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
            column: dial_code
        code:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
    lifecycleCallbacks: {  }
